---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: podinfo
  namespace: green-ns
spec:
  template:
    spec:
      containers:
      - name: podinfod
        image: ghcr.io/stefanprodan/podinfo:6.0.0
        env:
        - name: PODINFO_UI_COLOR
          value: "#000000"
...